server:
  port: 8763
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone:  http://127.0.0.1:8762/eureka/,http://127.0.0.1:8761/eureka/



