spring:
  profiles:
    active: peer1


eureka:
  server:
    enable-self-preservation: false #\u5173\u95ED\u81EA\u6211\u4FDD\u62A4
    eviction-interval-timer-in-ms: 30000  #\u6E05\u7406\u95F4\u9694\u8BBE\u4E3A30s
