server:
  port: 8761


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8762/eureka/,http://127.0.0.1:8761/eureka/
  instance:
    hostname: test
    prefer-ip-address: true



spring:
  application:
    name: eureka-server
  freemarker:
    prefer-file-system-access: false